Dashboard - Part 1
Added:
apex-charts

Dashboard:
On the dashboard page, for the graphs I added apexcharts, and with the addition of the graphs the visual styling of the dashboard is almost done. It's still static but by the end of the development it will be dynamic.

Having some type errors in :
components/Sidebar.tsx/ at Link 'align'
error: ((property) align: string
Type '{ children: Element[]; display: "flex"; align: string; }' is not assignable to type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>, keyof LinkProps> & LinkProps & { ...; }'.
  Property 'align' does not exist on type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>, keyof LinkProps> & LinkProps & { ...; }'.ts(2322))

pages/dashboard.tsx/ at SimpleGrid 'align'
error: ((property) align: string
Type '{ children: Element[]; flex: string; gap: "4"; minChildWidth: "320px"; align: string; }' is not assignable to type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, keyof SimpleGridProps> & SimpleGridProps & { ...; }'.
  Property 'align' does not exist on type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, keyof SimpleGridProps> & SimpleGridProps & { ...; }'.ts(2322))

pages/dashboard.tsx/ at Chart 'options'
error: ((property) Props.options?: ApexCharts.ApexOptions
Type '{ chart: { toolbar: { show: boolean; }; zoom: { enabled: boolean; }; foreColor: any; }; grid: { show: boolean; }; dataLabels: { enabled: boolean; }; tooltip: { enabled: boolean; }; xaxis: { type: string; axisBorder: { ...; }; axisTicks: { ...; }; categories: string[]; }; fill: { ...; }; }' is not assignable to type 'ApexOptions'.
  The types of 'xaxis.type' are incompatible between these types.
    Type 'string' is not assignable to type '"datetime" | "category" | "numeric"'.ts(2322)
react-apexcharts.d.ts(28, 5): The expected type comes from property 'options' which is declared here on type 'IntrinsicAttributes & Props & { children?: ReactNode; }')